techdocs:
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${TECHDOCS_BUCKET}
      bucketRootPath: '/'
      accountId: ${AWS_ACCOUNT_ID}
      credentials:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}
    requestUrl:
      type: "remote"
