#!/bin/bash
# This is an example script
# Carregar variáveis do .env
export $(grep -v '^#' .env | xargs)

# Prepare
git clone "https://github.com/carlosrobertodevops/eks-cluster-docs.git"
cd repo

TECHDOCS_BUCKET=$TECHDOCS_S3_BUCKET_NAME
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_REGION=$AWS_REGION

NAMESPACE="default"
KIND="Component"
NAME="eks-cluster-docs"

# Install @techdocs/cli, mkdocs and mkdocs plugins
npm install -g @techdocs/cli
pip install "mkdocs-techdocs-core==1.*"

# Generate
techdocs-cli generate --no-docker

# Publish
# techdocs-cli publish --publisher-type awsS3 --storage-name ${TECHDOCS_BUCKET} --entity <${ENTITY_NAMESPACE}/${ENTITY_KIND}/${ENTITY_NAME} --verbose
techdocs-cli publish \
	--publisher-type awsS3 \
	--storage-name $TECHDOCS_BUCKET \
	--entity $NAMESPACE/$KIND/$NAME \
	--verbose

rm -rf "./eks-cluster-docs"
rm -rf "./site/"